name: Train Anime Rank Model

on:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anime-rank-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: pip install mlflow

      - name: Run mlflow project
        shell: bash
        run: |
          mlflow run MLProject -P n_estimators=150 -P max_depth=12

      - name: Get latest MLflow run_id
        shell: bash
        run: |
          echo "Fetching run_id..."
          RUN_ID=$(mlflow runs list --experiment-name anime-rank-project --order-by start_time desc | awk 'NR==2 {print $1}')
          echo "Latest run_id: $RUN_ID"
