name: Train Anime Rank Model

on:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow
          pip install mlflow scikit-learn pandas numpy imbalanced-learn matplotlib seaborn

      - name: Run mlflow project
        run: |
          mlflow run MLProject -P n_estimators=150 -P max_depth=12 --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          echo "Fetching run_id..."
          RUN_ID=$(mlflow runs list --experiment-name anime-rank-project --order-by start_time desc | awk 'NR==2 {print $1}')
          echo "Latest run_id: $RUN_ID"
