name: Train Anime Rank Model

on:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anime-rank-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow
        run: pip install mlflow

      - name: Run model training manually
        run: |
          conda activate anime-rank-env
          python MLProject/modelling.py --n_estimators 150 --max_depth 12
